Views
joyapisi/blog_app pull request #6
Opened 2023-07-20 20:30 UTC by joyapisi

## Work Done
- Use preprocessed HTML file with embedded Ruby code.
- Use layouts and templates for shared content.

2023-07-20 21:29 UTC, VICTOR-CHUKWU requested changes
Hi @joyapisi  👋  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost](https://media.giphy.com/media/R2m2NzVxQ3pbG/giphy.gif)

## Highlights
- Good PR
- Good commit
- All linters passed


## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-20 21:29 UTC, VICTOR-CHUKWU commented on app/views/users/index.html.erb
> +<% end %>
- [ ] kindly match the given wireframe 
your design :point_down: 
![Screenshot from 2023-07-20 22-18-20](https://github.com/joyapisi/blog_app/assets/66097371/ecc07b3d-1595-4f3c-a13f-2dc7f06f01e4)
wireframe :point_down: 
![Screenshot from 2023-07-20 22-19-45](https://github.com/joyapisi/blog_app/assets/66097371/bff15849-c287-4c13-ae10-a0b3080f6ca9)

2023-07-20 21:29 UTC, VICTOR-CHUKWU commented on app/views/users/show.html.erb
> +</div>
- [ ] kindly match the wireframe given 
your design :point_down: 
![Screenshot from 2023-07-20 22-23-31](https://github.com/joyapisi/blog_app/assets/66097371/45c7ac56-dcbe-4c6b-8fa0-01eb7d28965a)
wireframe :point_down: 
![Screenshot from 2023-07-20 22-23-13](https://github.com/joyapisi/blog_app/assets/66097371/090505f6-5f29-46dd-9f40-319ad5651f2c)

2023-07-20 21:29 UTC, VICTOR-CHUKWU commented on app/views/posts/index.html.erb
> +</div>
- [ ] When I navigate to the post page of a user posts page I get an error
![Screenshot from 2023-07-20 22-25-59](https://github.com/joyapisi/blog_app/assets/66097371/6ecbadb9-4d10-4fd3-9c7a-672e04ccf452)

2023-07-21 01:12 UTC, Reem-lab reviewed
Hi @joyapisi, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has the wrong link for the activity since you submitted it in add form activity and the views milestone so please kae sure you submit it in the right activity ✨💪🏻🙏🏻🤩

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-07-21 02:10 UTC, t-yanick approved these changes
# STATUS: MILESTONE APPROVED :1st_place_medal: 

Hi @joyapisi , 

### Great job !!!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Requested changes implemented

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-22 09:17 UTC, merged