Capybara nplus1
joyapisi/blog_app pull request #8
Opened 2023-07-25 08:43 UTC by joyapisi

## Work Done

- Solve n+1 problem
-

2023-07-25 10:44 UTC, julie-ify reviewed
Hi @joyapisi and @Kwaku28,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

* Kindly remove the walkthrough video header link if you have no video to present.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-07-25 12:49 UTC, christianbiring1 requested changes
Hi @joyapisi @Kwaku28 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
# STATUS: REQUEST CHANGES :recycle: 


## Highlights
- [ ] Great work on solving the n+1 queries problem :+1: 
- [ ] Descriptive PR `title` and `summary` :+1: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-25 12:49 UTC, christianbiring1 commented on app/controllers/posts_controller.rb
> +    @posts = Post.includes(:comments).where(author_id: params[:id])
- [ ] Great work for solving the n+1 query problem by includes a reference to your post :+1:

2023-07-25 12:49 UTC, christianbiring1 commented on spec/views/users/index_spec.rb
> +    User.create(name: 'Jane Smith', email: 'jane@example.com', password: 'password')
- [ ] Kindly make sure you are using the correct attribute on the instance of your elements. As you may see in your schema, there are no such attributes on user, I mean `email`, `password` rather you have `photo`, `bio` ... Please make sure you fix that.
That's why the test is failing:
![image](https://github.com/joyapisi/blog_app/assets/97100091/393f9206-1f9c-4e61-a696-7497db850825)

2023-07-25 12:49 UTC, christianbiring1 commented on spec/views/users/show_spec.rb
> +  end
- [ ] Kindly make sure you ask what have been asked in the project requirements as you may see [here](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/intergration_spec_and_n_1_project.md#:~:text=corresponding%20wireframe%20view%3A-,Integration%20specs,-Use%20Capybara%20to) 
- [ ] You are supposed to use `Capybara` to do the integration test. You may consider checking [this article](https://www.codewithjason.com/rails-testing-hello-world-using-rspec-capybara/) if you have no idea about what to do.

2023-07-26 22:02 UTC, codecaiine commented
Hi @joyapisi can you go on slack ? I sent you a message

2023-07-26 22:17 UTC, codecaiine requested changes
Hi @joyapisi , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- Good requested changes implementation ✔️ 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-26 22:17 UTC, codecaiine commented on app/controllers/likes_controller.rb
> +    # @like = Like.find_or_create_by(author_id: current_user.id, post_id: params[:post_id])
- [ ] [OPTIONAL] Please remove all commented code from your codebase because it's a bad practice to commit commented-out code. That's what version control is for. If you need that code back, just fetch it from the repo :smile:

2023-07-26 22:17 UTC, codecaiine commented on db/migrate/20230724203021_add_posts_count_to_users.rb
> +class AddCounterCaches < ActiveRecord::Migration[7.0]
- [ ] When I ran the migration I am getting this errors as you can see on the screenshot below 👇  that make impssible to run the Tests. I would like to recommend you to double-check the name of your migration  and make sure that all the tests are passed before submitting it as required for this project and previous reviewer 😄 

![unnamed (2)](https://github.com/joyapisi/blog_app/assets/6615394/a7da3a54-c936-46fb-a5d7-1f9cbe749549)

2023-07-26 22:33 UTC, joyapisi commented
> Hi @joyapisi can you go on slack ? I sent you a message

Hello. Yes. I am available

2023-07-27 01:19 UTC, Davidosky007 requested changes
Hi @joyapisi 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
* N+1 issue solved 👍 
* Well written PR 👍 
* No linter errors 👍 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @davidosky007 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-27 01:19 UTC, Davidosky007 commented on db/migrate/20230713113935_create_users.rb
> +    add_column :users, :posts_count, :integer, default: 0
* This new change you implemented is causing an error in your integration tests as your tests try to create users using `posts_counter` but keeps clashing with this column being added `:posts_count` i strongly suggest that you ensure that the column name matches the one written in your schema and tests( which is `posts_counter`) 
![image](https://github.com/joyapisi/blog_app/assets/52497246/9391e3e5-7a2a-4a2c-bc42-e8c73324d631)
![image](https://github.com/joyapisi/blog_app/assets/52497246/0329839e-df0a-4d9b-a586-092bbffe0ff4)
![image](https://github.com/joyapisi/blog_app/assets/52497246/ad988e8b-f020-4112-8779-fc3fd08c8dfc)

2023-07-27 15:38 UTC, DammyShittu approved these changes
Hi @joyapisi and @christianbiring1,

## APPROVED 🟢

## Highlights
✔️ Project met all technical requirements

Great implementation of all the requirements in this milestone. 👏 

_You have done an amazing job 👍_

Your project is complete!  There is nothing else to say other than... it's time to merge it. :shipit: 

Congratulations! 🎉 

## CHEERS AND HAPPY CODING!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-27 15:53 UTC, merged